#!/bin/bash

# ---------- 64 BIT -------------- #
#
ISO="../Bliss-Surface-v14.10.3-x86_64-OFFICIAL-foss-20241013.iso"
#
qemu-system-x86_64 -enable-kvm \
    -cdrom $ISO \
    -boot menu=on \
    -drive file=Image.img \
    -m 8G \
    -cpu host \
    -vga virtio \
    -display sdl,gl=on \
    -serial none \
    -smp cores=8 \
    -virtfs local,path=./shared,mount_tag=shared,security_model=mapped-xattr \

